#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:30:00

#SBATCH --job-name=bl_mne_noise_cov
#SBATCH --ntasks-per-node=1
#SBATCH --mem=16G
#SBATCH --time=00:30:00

set -x
set -e

mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_dir_report

if [ -f /usr/bin/singularity ]; then
    singularity exec docker://brainlife/mne:1.0.2 python3 main.py
else
    python3 main.py
fi
