#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=02:00:00
#PBS -l vmem=32gb

#SBATCH --job-name=bl_mne_noise_cov
#SBATCH --ntasks-per-node=1
#SBATCH --mem=32G
#SBATCH --time=02:00:00

set -x
set -e

singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py
